### PR TITLE
Added cent-os to CI tests

### PR DESCRIPTION
**Pull request by martinkilbinger**
## Summary

Continuous integration is now also testing CENT-OS, useful since candide runs on that OS.

Solves #633 

## Reviewer Checklist

> Reviewers should tick the following boxes before approving and merging the PR.

- [ ] The PR targets the `develop` branch
- [ ] The PR is assigned to the developer
- [ ] The PR has appropriate labels
- [ ] The PR is included in appropriate projects and/or milestones
- [ ] The PR includes a clear description of the proposed changes
- [ ] If the PR addresses an open issue the description includes "closes #<ISSUE NUMBER>"
- [ ] The code and documentation style match the current standards
- [ ] Documentation has been added/updated consistently with the code
- [ ] All CI tests are passing
- [ ] API docs have been built and checked at least once (if relevant)
- [ ] All changed files have been checked and comments provided to the developer
- [ ] All of the reviewer's comments have been satisfactorily addressed by the developer

### CODE REVIEW

**Comment by martinkilbinger** [comment]
Not sure it is working. The CI test gets stuck at
`Waiting for a runner to pick up this job... `

**Comment by sfarrens** [comment]
@martinkilbinger this might mean that they don't have many servers available with that OS. I don't even see `centos-latest` listed as one of the [available runners](https://github.com/actions/runner-images#available-images). Did you check that this image exists somewhere?

**Comment by martinkilbinger** [comment]
I could not find it either anywhere. So maybe we cannot run this test.

**Comment by sfarrens** [comment]
In principle, we could set up a [Self-Hosted Runner](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) on a machine where we can put a CentOS image. Then we could probably make a separate manually triggered CI workflow for running tests with this runner.

This should not be too difficult to set up, but I don't think it is the most urgent issue to resolve.

**Comment by martinkilbinger** [comment]
We can leave this issue open; I removed it from the release milestone.

**Pull request closed without merging**
